### ISSUE TITLE
where is the wheels.yml?

### ISSUE THREAD

**Issue by caishanli** [pybind/scikit_build_example#5]
Hi:
   I can't find wheels.yml anywhere, could you help me?

**Comment by caishanli** [comment]
I find it.
[wheels.yml](https://github.com/pybind/cmake_example/blob/master/.github/workflows/wheels.yml)

**Comment by bdice** [comment]
I think this is still a valid issue -- the docs for cibuildwheel link to this repository but the `wheels.yml` file mentioned in the README is missing. The link posted by @caishanli above points outside of this repository, and that repo doesn't use scikit-build. The combination of scikit-build and cibuildwheel was my motivation for seeing this example. https://cibuildwheel.readthedocs.io/en/stable/working-examples/

**Comment by henryiii** [comment]
This was written originally, but didn't support all setups (windows-2019 is not supported even by our cmake_example). I can see if I can (finally) add it. Hoping to help improve scikit-build in the long term.

**Comment by bdice** [comment]
@henryiii Feel free to ask for help/review on #6 if you want a hand!

**Comment by henryiii** [comment]
If you have an idea about how to enable Windows or use the new FindPython instead of the old one, happy to have advice! Otherwise, I'll just remove the Windows wheels for now and use classic FindPythonLibs/Interp until we can improve scikit-build itself a bit.
